### ISSUE TITLE
Plasttic v3.0: Revert to Dependabot

### ISSUE THREAD

**Issue by tojeiro-me** [tojeiro-me/Plasttic#775]
- Could not make it work with PNPM

##Tasks:
- [x] Re-triger dependabot insights/dependency grapch/dependabot
- [ ] Signed Commits (plasttic_ci.yml)
- [x] Auto-marge https://github.com/marketplace/actions/dependabot-auto-merge

**Comment by tojeiro-me** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Dependabot](https://trello.com/c/kYfeWHhq/4-dependabot)
